# Generated by Django 5.2.14 on 2026-05-27 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProcedureSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_id', models.UUIDField(help_text='ID del procedimiento clínico (clinical_procedures.id)')),
                ('quantity_used', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Insumo utilizado en procedimiento',
                'verbose_name_plural': 'Insumos utilizados en procedimientos',
                'db_table': 'clinical_procedures_supplies',
            },
        ),
        migrations.CreateModel(
            name='ConsultationSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_id', models.UUIDField(help_text='ID de la consulta (debe existir en la tabla consultations)')),
                ('quantity_used', models.IntegerField()),
            ],
            options={
                'db_table': 'consultation_supplies',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('APPROVED', 'Aprobada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('MEDICINE', 'Medicamento'), ('VACCINE', 'Vacuna'), ('CONSUMABLE', 'Consumible'), ('EQUIPMENT', 'Equipo')], max_length=50)),
                ('min_stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'supplies',
            },
        ),
        migrations.CreateModel(
            name='SupplyBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('initial_stock', models.IntegerField()),
                ('current_stock', models.IntegerField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supply_batches',
            },
        ),
    ]
