# Generated by Django 5.2.14 on 2026-05-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='stock.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='stock.supply'),
        ),
        migrations.AddField(
            model_name='supplybatch',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.supply'),
        ),
        migrations.AddField(
            model_name='consultationsupply',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_usages', to='stock.supplybatch'),
        ),
        migrations.AddField(
            model_name='clinicalproceduresupply',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_usages', to='stock.supplybatch'),
        ),
        migrations.AlterUniqueTogether(
            name='consultationsupply',
            unique_together={('consultation_id', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='clinicalproceduresupply',
            unique_together={('procedure_id', 'batch')},
        ),
    ]
