# Generated by Django 5.2.14 on 2026-05-27 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('BOOKED', 'Reservado'), ('BLOCKED', 'Bloqueado')], default='FREE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_visit', models.TextField(help_text='Motivo de la consulta')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'En Sala'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=15)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='VetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.veterinarian')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='appointments.vetschedule'),
        ),
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=10)),
                ('status', models.CharField(choices=[('WAITING', 'Esperando'), ('ATTENDING', 'En Atención'), ('DONE', 'Finalizado'), ('ABANDONED', 'Abandonó')], default='WAITING', max_length=10)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
