# Generated by Django 5.2.14 on 2026-05-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateField()),
                ('allergies_history', models.TextField()),
                ('medical_alerts', models.TextField()),
            ],
            options={
                'db_table': 'clinical_records',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species_breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('current_weight', models.FloatField()),
                ('physical_marks', models.CharField(max_length=255)),
                ('microchip_id', models.CharField(max_length=50)),
                ('reproductive_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='VaccinationDewormingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VACCINE', 'Vacuna'), ('DEWORMING', 'Desparasitante')], max_length=15)),
                ('dose', models.CharField(max_length=50)),
                ('applied_date', models.DateField()),
                ('sanitary_batch', models.CharField(max_length=100)),
                ('next_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('target_age_days', models.IntegerField(help_text='Edad óptima sugerida en días')),
            ],
        ),
    ]
