# Generated by Django 5.2.14 on 2026-06-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationdewormingevent',
            name='vaccine_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
